baseURL = "https://jackdolgin.org"
languageCode = "en-us"
title = "Jack Dolgin"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle = "pygments"

summaryLength = 50

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.nav]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "about"
    url = "/about/"
    weight = 2
  [[menu.nav]]
    name = "blog"
    url = "/blog/"
    weight = 3
  [[menu.nav]]
    name = "cv [pdf]"
    url = "/vita/dolgin_cv.pdf"
    weight = 4
  [[menu.nav]]
    name = "contact"
    url = "/contact/"
    weight = 5

[blackfriday]
      plainIDAnchors = true
      hrefTargetBlank = true

[params]
  fontsUseGoogleApis = "true"
  includeBootstrapJs = false
  showActiveNav = false
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = ""
  footerText = ""
  hideFooter = true

[Social]
  twitter = "jbdolg"

[params.googleApiFonts.family]
  tagsText        = [ "html", "body", "time" ]
  tagsHeading     = [ "h1", "h2", "h3", "h4", "h5", "h6" ]
  tagsMono        = [ "pre", "code", "samp" ]
  fallbackText    = "html"
  fallbackHeading = "h1"
  fallbackMono    = "pre"

[params.googleApiFonts.family.html]
  sans-serif = "Inconsolata"
[params.googleApiFonts.family.h1]
  sans-serif = "Inconsolata"
[params.googleApiFonts.family.samp]
  sans-serif = "Inconsolata"
[params.googleApiFonts.family.code]
  sans-serif = "Ubuntu Mono"
