---
geometry: "left=.3cm,right=4.6cm,top=3cm,bottom=4.5cm"

output:
  pdf_document:
    latex_engine: xelatex
    extra_dependencies: ["xcolor", "hyperref", "fontspec", "array", "setspace", "longtable", "ifthen"]
    pandoc_args: "--pdf-engine-opt=--enable-write18"
header-includes:
  \usepackage{fancyhdr}
  \usepackage{datetime}
  \newdateformat{monthyeardate}{\monthname[\THEMONTH], \THEYEAR}
  \renewcommand{\headrulewidth}{0pt}
  \pagestyle{fancy}
  \fancyfoot[LE,RO]{\ifthenelse{\value{page}=1}{\monthyeardate\today}{\pagestyle{empty}}}
  
---

\setmainfont[Color={444444}]{Humanist 521 Light BT}
\makeatletter
\def\Hy@href#{\addfontfeatures{Color=047464}\hyper@normalise\href@}

\newfontfamily\MyRed[Color={a41414}]{Gill Sans Nova Cn Bold}
\def\sectitle{\MyRed \fontsize{12}{10} \selectfont}
\newfontfamily\MyName [Color={444444}]{Adobe Garamond Pro Bold}

\def\jmp{[.5cm]}

\def\ind{\hspace{.37cm} \hangindent=.45cm }

\def\HeadSpace{.15\textwidth}

\def\websiteURL{https://jackdolgin.org}
\def\presentationExtension{/presentations/}
\def\publicationExtension{/publications/}



\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.6\textwidth} >{\raggedleft\arraybackslash}p{.25\textwidth}}
          & \begingroup\MyName \fontsize{20}{10} \selectfont Jack Dolgin \endgroup  &
          \\
          & Somers Family Hall 1125                                                 & \href{https://twitter.com/jbdolg}{@jbdolg}
          \\
          & 1 Brookings Drive                                                       & \href{mailto:jdolgin@wustl.edu}{jdolgin@wustl.edu}
          \\
          & St. Louis, MO 63130                                                     & \href{\websiteURL}{jackdolgin.org}
\end{longtable}



\setmainfont[Color={444444}]{Adobe Garamond Pro}



\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.6\textwidth} >{\raggedleft\arraybackslash}p{.25\textwidth}}
\begingroup\sectitle EDUCATION\endgroup  & Washington University in St. Louis                                                                & St. Louis, MO
                                         \\
                                         & \ind Ph.D., Psychological \& Brain Sciences                                                       & 2020 -
                                         \\
                                         & \ind Advisor: Wouter Kool                                                                         &
                                         \\
                                         \\
                                         & Duke University                                                                                   & Durham, NC
                                         \\
                                         & \ind B.S., Psychology, with Distinction                                                           & 2014 - 2018
                                         \\
                                         & \ind Thesis: \href{https://hdl.handle.net/10161/20686}{Separating the influence of budget and numeric priming on willingness to pay}  &            
\end{longtable}
 \renewcommand{\arraystretch}{1.5}



\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.6\textwidth} >{\raggedleft\arraybackslash}p{.25\textwidth}}
\begingroup\sectitle EXPERIENCE\endgroup  & Duke University                                                               & Durham, NC
                                          \\
                                          & \ind Lab Manager, Egner Lab                                                   & 2018 - 2020
                                          \\
                                          & \ind Research Assistant, Huettel Lab                                          & 2017 - 2018
                                          \\
                                          & \ind Research Assistant, Cognitive-Behavioral Research and Treatment Program  & 2016
\end{longtable}




\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.05\textwidth} >{\raggedright\arraybackslash}p{0.6\textwidth} >{\raggedright\arraybackslash}p{0.15\textwidth}}
\begingroup\sectitle GRANTS\endgroup  & 2020  & Graduate Research Fellowship from the National Science Foundation (\$138,000)  &
                                      \\
                                      & 2019  & Interdisciplinary Behavioral Research Center Mini-Grant from Duke University (\$600)  &
                                      \\
                                      & 2018  & Faculty Seed Grant from Duke University, with Peter S. Whitehead and Tobias Egner (\$34,000)  &
\end{longtable}




\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.05\textwidth} >{\raggedright\arraybackslash}p{0.3\textwidth} >{\raggedright\arraybackslash}p{0.45\textwidth}}
\begingroup\sectitle AWARDS\endgroup  & 2017  & \href{https://psychandneuro.duke.edu/summer-vertical-integration-program-vip}{Vertical Integration Program} \newline Duke University (\$3,500) & Selected for funding for a summer of research at Duke University before my senior year                                                                
                                      \\
                                      & 2016  & \href{https://library.duke.edu/research/awards/aptman}{Lowell Aptman Prize} \newline Duke University (\$1,000)                                & Awarded the best non-senior-thesis research \href{https://hdl.handle.net/10161/16739}{paper} in any subject among all Duke students
                                      \\
                                      & 2015  & \href{https://library.duke.edu/research/awards/holsti}{Ole R. Holsti Prize} \newline Duke University (\$1,000) & Awarded, for a \href{http://hdl.handle.net/10161/10217}{separate paper}, the best research paper in political science using primary sources among all freshmen and sophomores at Duke University
\end{longtable}




\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.8\textwidth}}
\begingroup\sectitle PUBLICATIONS\endgroup  & 
                                           Bejjani, C., \textbf{Dolgin, J.}, Zhang, Z., and Egner, T. (2020). \href{\websiteURL \publicationExtension 2020pub_BejjaniDolginZhangEgner.pdf}{Disentangling the roles of cue visibility and knowledge in adjusting cognitive control: A preregistered direct replication of the Farooqui and Manly (2015) study}. \emph{Psychological Science}, \emph{31}(4), 468-479.
                                           \\
                                           & \textbf{In Progress}                                                                                             \\
                                           & Amasino, D., \textbf{Dolgin, J.}, and Huettel, S.A. Eyes on the budget size: Attention to variable budgets influences mental accounting in consumer choice. In preparation (draft available upon request).
                                           \\
                                           & \textbf{Dolgin, J.} and Egner, T. In preparation (\href{https://jackdolgin.shinyapps.io/rhythmic_attention/}{data available via interactive Shiny app}). Monitoring multiple external locations may not induce rhythmic attention.
                                           \\
                                           & \textbf{Dolgin, J.} and Henne, P. In preparation. Statistical norms and agent's epistemic state influence causal selection in real-world animation.
\end{longtable}




\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.8\textwidth}}
{\begingroup\sectitle TALKS, PRESENTATIONS, \& WORKSHOPS\endgroup}  & \textbf{Refereed} \begin{spacing}{1.5} \par \end{spacing} Amasino, D., \textbf{Dolgin, J.}, and Huettel, S.A. (2019, June). Individual differences in the use of variable budget information in consumer choice. Talk delivered by D.A. at the 9th annual Interdisciplinary Symposium on Neuroscience, Durham, NC.
                                                        \\
                                                        & Amasino, D., \textbf{Dolgin, J.}, and Huettel, S.A. (2019, May). \href{\websiteURL \presentationExtension 2019pr_AmasinoDolginHuettel.pdf}{Individual differences in the use of variable budget information in consumer choice}. Poster presented by J.D. at the 31st annual meeting of the Association for Psychological Science, Washington, D.C.
                                                        \\
                                                        & \textbf{Dolgin, J.}, Bejjani, C., Zhang, Z., and Egner, T. (2019, May). \href{\websiteURL \presentationExtension 2019pr_DolginBejjaniZhangEgner.pdf}{Disentangling the roles of cue visibility and knowledge in learning cognitive control}. Poster presented by J.D. at the 31st annual meeting of the Association for Psychological Science, Washington, D.C.
                                                        \\
                                                        & Zhang, Z., Bejjani, C., \textbf{Dolgin, J.}, and Egner, T. (2019, Mar.). \href{\websiteURL \presentationExtension 2019pr_ZhangBejjaniDolginEgner.pdf}{Disentangling the roles of cue visibility and knowledge in learning cognitive control}. Poster presented by Z.Z. and J.D. at the 26th annual meeting of the Cognitive Neuroscience Society, San Francisco, CA.
                                                        \\
                                                        & Amasino, D., \textbf{Dolgin, J.}, and Huettel, S.A. (2018, Oct.). \href{\websiteURL \presentationExtension 2018pr_AmasinoDolginHuettel.pdf}{Individual differences in the use of variable budget information in consumer choice}. Poster presented by D.A. at the 16th annual meeting of the Society for NeuroEconomics, Philadelphia, PA.
                                                        \\
                                                        & \textbf{Non-Refereed}
                                                        \\
                                                        & \textbf{Dolgin, J.} (2020, April). \href{\websiteURL \presentationExtension intro-to-shiny.html}{An introduction to Shiny apps}. Workshop delivered by J.D. at the Duke Center for Cognitive Neuroscience Journal Club, virtually.
                                                        \\
                                                        & Zhang, Z., Bejjani, C., Chiu, Y.C., \textbf{Dolgin, J.}, and Egner, T. (2019, July). \href{\websiteURL \presentationExtension 2019pr_ZhangBejjaniChiuDolginEgner.pdf}{Neural evidence of control state reinstatement: an fMRI study}. Poster presented by Z.Z. at the Duke Summer Undergraduate Research Showcase, Durham, NC.
                                                        \\
                                                        & \textbf{Dolgin, J.} (2019, May). NCAA women’s basketball as a proxy for gender differences in verbal aggression. Talk delivered by J.D. at the Duke Center for Cognitive Neuroscience Data Blitz, Chapel Hill, NC.
                                                        \\
                                                        & \textbf{Dolgin, J.}, Amasino, D., and Huettel, S.A. (2018, Apr.). \href{\websiteURL \presentationExtension 2018pr_DolginAmasinoHuettel.pdf}{Separating the influence of budget and numeric priming on willingness to pay}. Poster presented by J.D. at the Duke Visible Thinking Poster Fair, Durham, NC.
                                                        \\
                                                        & \textbf{Dolgin, J.}, Amasino, D., and Huettel, S.A. (2017, July). \href{\websiteURL \presentationExtension 2017pr_DolginAmasinoHuettel.pdf}{Budget’s Effect on consumers’ willingness-to-pay}. Poster presented by Dolgin at the Duke Vertical Integration Program Poster Fair, Durham, NC.
\end{longtable}




\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.35\textwidth} >{\raggedright\arraybackslash}p{0.45\textwidth}}
\begingroup\sectitle SIDE PROJECTS\endgroup  & \textbf{Dolgin, J.}, Whitehead, P.S., Vieth, A.Z. (In Preparation). NCAA women’s basketball reveals men as more verbally aggressive. & Foray into 50,000 basketball games with web-scraping—finishing a project idea I had to propose for Dr. Vieth’s class as an undergraduate—to complete the first observational study in adults to date on differences in verbal aggression between genders.
                                             \\
                                             & Butchireddygari, L., \textbf{Dolgin, J.} (2018). \href{https://www.dukechronicle.com/article/2018/01/is-greek-life-at-duke-as-homogenous-as-you-think}{Is Greek life at Duke as homogeneous as you think?} Duke Chronicle.                  & My coauthor and I collected over 30 variables on all 1,700 students in Duke’s class of 2018 to analyze trends in the demographics of members of Greek life, and we posted all our publicly-collected data to a repository and I analyzed it in an interactive \href{https://jackdolgin.shinyapps.io/GreekLifeDemographics/}{Shiny app}.
                                            \\
                                            & \textbf{Dolgin, J.} (2017). \href{http://dewitt.sanford.duke.edu/wp-content/uploads/2017/02/Dolgin-blog-This-week-in-Duke-History.pdf}{This Week in Duke Sports History}. Duke Chronicle.
                                            & My work documenting a zany fact in Duke sports history for an entire year was a finalist in Duke’s annual award for a journalism project or article across all of Duke’s undergraduates, including journalism certificate students and the rest of the school.
\end{longtable}




\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.11\textwidth} >{\raggedright\arraybackslash}p{0.21\textwidth} >{\raggedright\arraybackslash}p{0.45\textwidth}}
\begingroup\sectitle OTHER EXPERIENCES\endgroup  & 2019 -  & \href{https://www.techgirlz.org/}{TechGirlz} \newline Volunteer & Develop Python and R curricula that I and others in the organization teach to middle school girls.                                                                
                                                  \\
                                                  & 2014 - 2018  & \href{https://www.dukechronicle.com/search?a=1&au=Jack+Dolgin&ty=article}{Duke Chronicle} \newline Associate Editor & Wrote over 200 articles for the Duke student paper. I edited others’ writing, performed \href{https://www.dukechronicle.com/article/2017/04/school-vs-sports-which-really-comes-first-for-duke-athletes}{three} \href{https://www.dukechronicle.com/article/2018/01/is-greek-life-at-duke-as-homogenous-as-you-think}{data-driven} \href{https://www.dukechronicle.com/article/2018/05/are-slgs-as-diverse-as-you-think}{investigations}, covered events in 11 states, \href{https://www.dukechronicle.com/multimedia/314d8ec3-5a4c-4d22-8852-2b1e196a366b}{took} \href{https://www.dukechronicle.com/multimedia/b9c1c8cd-dc3d-4093-bfa2-0935b7d92e8c}{photos} \href{https://www.dukechronicle.com/multimedia/6dbc6250-e44c-47a0-9590-55d3245b3c90}{of} \href{https://www.dukechronicle.com/multimedia/80a554ad-1989-4fe8-a355-056560c662a3}{a} \href{https://www.dukechronicle.com/multimedia/c28b0808-3a6c-42e1-8230-e6b96dcacf33}{Trump} \href{https://www.dukechronicle.com/multimedia/c28b0808-3a6c-42e1-8230-e6b96dcacf33}{rally} \href{https://www.dukechronicle.com/multimedia/47ef3ad6-1d74-47a3-b89a-57fa6122f3b7}{the} \href{https://www.dukechronicle.com/multimedia/d1083abc-8a08-4f49-afe3-f08d91cbf53d}{day} \href{https://www.dukechronicle.com/multimedia/bdc055ca-1ee5-4190-903d-d7c5e9e4f8c6}{before} \href{https://www.dukechronicle.com/multimedia/342f3393-0f81-4cae-9100-84b976f973d6}{the} \href{https://www.dukechronicle.com/multimedia/0d29f279-568c-4e33-9260-4c4f321598cb}{election}, \href{https://www.dukechronicle.com/article/2017/10/pinning-opponents-inside-the-20-yard-line-its-harder-than-it-looks}{produced} \href{https://www.dukechronicle.com/article/2017/09/they-call-themselves-ultras-look-like-crazies}{videos}, and received the Rolly C. Miller award for ``exhibit[ing] a warmth and collegiality that brings the staff closer together."
\end{longtable}




\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.05\textwidth} >{\raggedright\arraybackslash}p{0.6\textwidth} >{\raggedright\arraybackslash}p{0.15\textwidth}}
\begingroup\sectitle ADDITIONAL TRAINING\endgroup  & 2020  & \href{https://www.neuromatchacademy.org/}{Neuromatch Academy}, Interactive track  &
\end{longtable}




\begin{longtable}
{>{\raggedleft\arraybackslash}p{\HeadSpace} >{\raggedright\arraybackslash}p{0.8\textwidth}}
{\begingroup\sectitle SKILLS \& TOOLS\endgroup}  & \href{https://github.com/search?q=language%3AR+user%3Ajackdolgin&s=indexed&type=Code}{R}, \href{https://github.com/search?q=language%3APython+user%3Ajackdolgin&s=indexed&type=Code}{Python}, PsychoPy, \href{https://github.com/search?q=language%3AHTML+user%3Ajackdolgin&s=indexed&type=Code}{HTML}/\href{https://github.com/search?q=language%3AJavaScript+user%3Ajackdolgin&s=indexed&type=Code}{JavaScript}/\href{https://github.com/search?q=language%3ACSS+user%3Ajackdolgin&s=indexed&type=Code}{CSS}, fMRI, Eye Tracking (EyeLink, Tobii), Web-scraping
\end{longtable}
